# Generated by Django 4.0.3 on 2022-03-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.PositiveIntegerField(),
        ),
    ]
