# Generated by Django 4.0.3 on 2022-04-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-fecha',)},
        ),
    ]
