# Generated by Django 4.0.3 on 2022-03-21 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida')], default='comida', max_length=6)),
                ('precio', models.FloatField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
    ]
